### ISSUE TITLE
Bernoulli GLM Raw and Bernoulli GLM have same name

### ISSUE THREAD

**Issue by atiyo** [sbi-benchmark/sbibm#17]
Hello! Thanks for building out and maintaining this package :)

Because of how the name of `bernoulli_glm_raw` [is initialised](https://github.com/sbi-benchmark/sbibm/blob/074e06a3335371ff88739e89711d2ebf2d4d912f/sbibm/tasks/bernoulli_glm/task.py#L34), it always gets the same name as `bernoulli_glm`.

```python
In [26]:     sbibm.tasks.get_task('bernoulli_glm').name
Out[26]: 'bernoulli_glm'

In [27]:     sbibm.tasks.get_task('bernoulli_glm_raw').name
Out[27]: 'bernoulli_glm'
```

Is this intended? In the results dataframe, I can see it referred to as `bernoulli_glm_raw`.
```python
In [30]: sbibm.get_results()
Out[30]:
                         task  ...                                folder
0               bernoulli_glm  ...  09ce89a2-3a5b-49d8-8942-f2a5f925674d
1               bernoulli_glm  ...  6d4b9630-51ae-497d-b74f-581b108910b6
2            gaussian_mixture  ...  6b3342b4-10a4-4933-8ad5-781e97eff7be
3                   two_moons  ...  0d71ce91-5f5e-4d14-b68d-53cd6710ec17
4           bernoulli_glm_raw  ...  be9320d9-53d5-44c1-9f25-6889222b5a61
```

**Comment by jan-matthis** [comment]
Hi @atiyo, thanks for pointing this out! It's not intended and should be fixed
