### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by DongxiaW** [sbi-benchmark/sbibm#35]
Hi, I'm trying the run the code but get a NotImplementedError. It is appreciated if you could help solve the issue. The error message is attached here
<img width="1141" alt="error_info" src="https://user-images.githubusercontent.com/36138851/141661115-322c0ffb-3dab-4a86-88e7-9ef82ef77277.png">

**Comment by jan-matthis** [comment]
Thanks for reporting this, @DongxiaW. This is indeed a bug, which is due to `sbi` handling transforms as well (a new feature introduced in v0.17.0). I'm currently looking into the best way to solve this.
