### ISSUE TITLE
updating to sbi v0.18.0?

### ISSUE THREAD

**Issue by psteinb** [sbi-benchmark/sbibm#48]
`sbi 0.18.0` brought in [tons of changes](https://github.com/mackelab/sbi/releases/tag/v0.18.0). I was wondering if there are any plans to adopt those? If so, it might be useful to reflect performance changes in the rendered results. 

For example, it might be worth considering to make the sbi version an additional field switch, e.g. like the `Task` currently.

**Comment by jan-matthis** [comment]
Currently, there are no plans to adopt `sbibm` to the new `sbi` API. A PR would definitely be welcome! 

Maintaining backward compatibility across different versions of `sbi` and a field switch would be a neat feature, but we are likely to end up with lots of duplicate code. In addition, we'd need to run tests against all different supported versions. My tendency would thus be to only support a single version of `sbi`. If one wanted to use an older version of `sbi` for some reason, one would checkout an older version of `sbibm` as well.

**Comment by psteinb** [comment]
I think there are 2 levels of abstracting the `sbi` version here:
- cater to it within `sbibm` through field switches and if-clause hell. I totally agree, that this can cause quite some headaches and boiler plate code. The runtime cost for the tests is also considerable.
- on the level of the benchmark data

I think fixing a singular `sbi` version to a singular `sbibm` is the way forward. But then, the benchmark data needs to honor this, I believe.

**Comment by michaeldeistler** [comment]
As a user, [the pin](https://github.com/sbi-benchmark/sbibm/blob/5cfd0b36e7813e48464c5f4ba3e0767261e043c7/setup.py#L32) to `v0.17.2` is sometimes quite annoying since it always downgrades my `sbi` installation to v0.17.2 whenever I install the benchmark.

How about putting the [entire algorithms folder](https://github.com/sbi-benchmark/sbibm/tree/main/sbibm/algorithms) into a separate repo? And then simply
```python
from sbibm_algorithms import rej_abc  # instead of from sbibm.algorithms import rej_abc
```

**Comment by michaeldeistler** [comment]
Or one could simply dropping the pin and throw a warning in the [`run` method](https://github.com/sbi-benchmark/sbibm/blob/5cfd0b36e7813e48464c5f4ba3e0767261e043c7/sbibm/algorithms/sbi/snpe.py#L17) if the detected sbi version is not 0.17.2

**Comment by jan-matthis** [comment]
How about installing with `--no-deps`?

**Comment by michaeldeistler** [comment]
I did not know about this and it does the job, thanks!

It's still not ideal though because one has to install some deps manually (e.g. `diffeqtorch`). If anyone knows a way to ignore specific dependencies that would be great!
