### ISSUE TITLE
pip install fails in conda and virtual env

### ISSUE THREAD

**Issue by gsujan** [sbi-benchmark/sbibm#5]
Hi 

The pip install fails currently with the following error.

```
ERROR: Could not find a version that satisfies the requirement sbibm
ERROR: No matching distribution found for sbibm

```

I tried it in a conda env and also just python3 virutal env

**Comment by jan-matthis** [comment]
Hi @gsujan,

this is unexpected, installation via pip should work fine.

Could you try the following:
```bash
$ conda create -n sbibm_test python==3.8 -y
$ condo activate sbibm_test
$ pip install sbibm
```

Also, which operating system are you using?

**Comment by gsujan** [comment]
Thanks @jan-matthis 

For some reason, its working now. Not sure where the problem was. 

OS: Ubuntu 18.04
