### ISSUE TITLE
Adding observations for a new task

### ISSUE THREAD

**Issue by guillametlucia** [sbi-benchmark/sbibm#51]
Hi, i'm implementing a new task for a university project but i cannot seem to find the way to input my epxerimental data/observations. Do i add the csv file manually? Or is it meant to be created by the simulator? thank you

**Comment by jan-matthis** [comment]
For existing tasks, data/observations are created by calling `task._setup`, see https://github.com/sbi-benchmark/sbibm/blob/main/sbibm/tasks/task.py#L418-L462

**Comment by guillametlucia** [comment]
Hi, yes, thank you, I see that they are created there but I do not understand how this corresponds to 'real-life' data if it is being simulated using random sets of parameters sampled from the prior. I thought i was missing how somehow the true parameters were inputted manually somehow.

**Comment by guillametlucia** [comment]
I am trying to get the algorithms to infer 12 parameters that will make my sets of ODEs result in oscillations of protein and mRNA. This does not happen with any random set of parameters sampled from the prior, hence the need to either manually input true thetas or a dataset of the oscillating species, and I fail to see where in the code I would include this. Moreover, I don't understand why there are 10 sets of true parameters for any one task. Thanks for your help.
