### ISSUE TITLE
Recent update not in install version

### ISSUE THREAD

**Issue by JuliaLinhart** [sbi-benchmark/sbibm#61]
When installing `sbibm` via `pip install sbibm`, recent updates like changing `sbi.mcmc.mcmc` to `sbi.samplers.mcmc.mcmc` (#59) are not included.

**Comment by janfb** [comment]
Hi @JuliaLinhart and thanks for reporting this. We will make a new release of `sbibm` soon (once #54 in merged) that will be included in the installation via `pip`. In the meantime, you obtain the recent version by cloning the repo, checking out on `main` and installing locally using `pip install -e .`

**Comment by JuliaLinhart** [comment]
Okay, thanks a lot!

**Comment by jan-matthis** [comment]
Thanks for reporting, v1.1.0 is now released.
