### ISSUE TITLE
MNLE sbibm.get_task("ddm") NotImplementedError

### ISSUE THREAD

**Issue by Jaitoh** [sbi-benchmark/sbibm#64]
after installing the sbibm using pip (version 1.0.8) and trying to run the code from mnle repo
when calling the line `task = sbibm.get_task("ddm")`
it raise a not implemented error

**Comment by jan-matthis** [comment]
Hi Jaitoh, thank you for reaching out! The MNLE repo uses a [feature branch](https://github.com/mackelab/sbibm/tree/ddm-task) that has not been merged yet (see [`requirements.txt`](https://github.com/mackelab/mnle-for-ddms/blob/main/requirements.txt#L5)). If you run into trouble, please reopen this issue and @janfb can help out.
