### ISSUE TITLE
Missing future module error

### ISSUE THREAD

**Issue by Jimmyc776** [sbi-benchmark/sbibm#70]
Good morning.

Any idea how to handle this error? I cannot find a "future" module anywhere on this github. Is it something that needs to be installed from somewhere else? I'm running with python 3.11.9.

<img width="531" alt="Screenshot 2024-10-21 at 10 29 50 AM" src="https://github.com/user-attachments/assets/427c1369-13ba-4673-928a-e9574fc5fb66">

**Comment by janfb** [comment]
Thanks for reporting, I will have a look at this later this week.

**Comment by janfb** [comment]
Sorry for the delay @Jimmyc776 . I can reproduce the error by running

```bash
conda create -n sbibm python=3.11.9
conda activate sbibm
pip install pytest
pytest tests
```

It is fixed installing `future` (a package for bridging between python 2 and 3). 

```bash
pip install future
pytest tests
```

We will soon make a new release that fixes these installation-related issues.

**Comment by Jimmyc776** [comment]
That fixed it, thanks!
